name: CD

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["CI"]
  #   types:
  #     - completed

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: mlDemo-rg
          cluster-name: mlDemo-AKS

      - name: Deploy
        run: |
          kubectl apply -f deployment/namespace.yaml
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml